language: java
jdk:
  - oraclejdk8
before_script:
  - uname -a
  - mvn -version
  - ls ~/.m2
  - echo "@@@@@@" >> ~/.m2/settings.xml
  - cat ~/.m2/settings.xml
deploy:
  provider: gcs
  access_key_id: "GCS Interoperable Access Key ID"
  secret_access_key: "GCS Interoperable Access Secret"
  bucket: "GCS Bucket"
  skip_cleanup: true